---
title: "CV"
author: "Nathan Mietkiewicz, Ph. D."
email: Nathan.Mietkiewicz@Colorado.edu
output:
  pdf_document:
    latex_engine: pdflatex
    template: ~/Dropbox/Professional/portfolio/curriculum-vitae/docs/svm-latex-cv.tex
  html_document:
    df_print: paged
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 10pt
geometry: margin=1in
github: NateMietk
jobtitle: Postdoctoral Reserach Fellow, Earth Lab
linkcolor: black
fontawesome: yes
phone: 508 797 2940
address: 'University of Colorado · Boulder · 4001 Discovery Dr. '
urlcolor: black
web: nathanmietkiewicz.com
---
# Education

**Clark University, Worcester, MA**

- **Ph. D.**, Geography, 2012 - 2016
    - *Dissertation Title*: Interactions of spruce beetle outbreak and wildland fire in Colorado: legacies and future projections under a changing climate.
    - *Advisor*: Dr. Dominik Kulakowski
- **M.A.**, Geography, 2015
- **M.S.**, GIS for Development and Environment, 2010-2013
    - *Thesis*: A century of ecological change in a subalpine forest of the Swiss Alps.
    - *Advisors*: Dr. Dominik Kulakowski, Dr. John Rogan, Dr. Peter Bebi
**University of Maine, Orono, ME**
- **B.S.**, Earth Science, 2009

# Technology Proficiencies

**Applications**: RStudio, Jupyter Notebooks, Amazon Web Services (S3, EC2), ArcGIS Platform, QGis, IDRISI/Terrset, Adobe CS6 Illustrator

**Programming**: R (expert), Python (general understanding), RMarkdown, Docker, GitHub, UNIX Shell Programing (general understanding)

# Software and Dataset Development

**ICS-209-PLUS** - An all-hazards dataset mined from the US National Incident Management System 1999-2014. doi: 10.6084/m9.figshare.8048252.v8. url: https://figshare.com/articles/ICS209-PLUS_Cleaned_databases/8048252

**Fire Events Delineation (FIRED)** - Events-delineation algorithm used to derive fire events from the MODIS burned area product (MCD64A1) for the U.S. from 2001-19. In review.

**FIREDr** - R package to automatically download and process MODIS burned area product (MCD64A1). Unpublished. url: https://github.com/NateMietk/FIREDr

# Peer-reviewed Publications 

Rogan, J., Elmes, A., Rosenblum, H., **Mietkiewicz, N.**, Kulakowski, D., Stow, D. (under evaluation). *Drivers of fire ignition in Southern California Mediterranean-type Ecosystems*. Fire Ecology.

St. Denis, L, **Mietkiewicz, N**, Short, K C, Buckland, M, Balch, J K, (under evaluation) *ICS-209-PLUS - An all-hazards dataset mined from the US National Incident Management System 1999-2014*. Scientific Data.

**N. Mietkiewicz**, J. K. Balch, T. Schoennagel, S. Leyk, L. St. Denis, B. Bradley. (under evaluation) *In the line of fire: Consequences of human-ignited wildfires to homes in the U.S. (1992-2015)*. Science Advances.

Joseph, M. B., M. W. Rossi, **N. P. Mietkiewicz**, A. L. Mahood, M. E. Cattau, L. A. St. Denis, R. C. Nagy, V. Iglesias, J. T. Abatzoglou, and J. K. Balch. (2019) *Understanding and predicting extreme wildfires in the contiguous United States*. Ecological Applications. doi:10.1002/eap.1898.

Balch, J., T. Schoennagel, A. Williams, J. Abatzoglou, M. Cattau, **N. Mietkiewicz**, and L. St. Denis. 2018. *Switching on the Big Burn of 2017*. Fire 1.

**Mietkiewicz, N.**, D. Kulakowski, and T. T. Veblen 2018. *Pre‐outbreak forest conditions mediate the effects of spruce beetle outbreaks on fuels in subalpine forests of Colorado*. Ecological Applications 28:457-472.

**Mietkiewicz, N.**, D. Kulakowski, D. Rogan, and P. Bebi. 2017. *Long-term change in sub-alpine forest cover, tree line and species composition in the Swiss Alps*. Journal of Vegetation Science. 28:951-964. DOI: 10.1111/jvs.12561

Schoennagel, T., J. K. Balch, H. Brenkert-Smith, P. E. Dennison, B. J. Harvey, M. A. Krawchuk, **N. Mietkiewicz**, P. Morgan, M. A. Moritz, R. Rasker, M. G. Turner, and C. Whitlock. 2017. *Adapt to more wildfire in western North American forests as climate changes*. Proceedings of the National Academy of Sciences. 114:4582-4590.

**Mietkiewicz, N.** and D. Kulakowski. 2016. *Relative importance of climate and mountain pine beetle outbreaks on the occurrence of large wildfires in the western US*. Ecological Applications:10.1002/eap.1400

Bakaj, F., **N. Mietkiewicz**, T. T. Veblen, and D. Kulakowski. 2016. *The relative importance of tree and stand properties in susceptibility to spruce beetle outbreak in the mid-20th century*. Ecosphere 7(10):e01485. 10.1002/ecs2.1485 

Hart, S. J., T. T. Veblen, **N. Mietkiewicz**, and D. Kulakowski. 2015. *Negative Feedbacks on Bark Beetle Outbreaks: Widespread and Severe Spruce Beetle Infestation Restricts Subsequent Infestation*. PLoS ONE 10:e0127975.

# Pre-prints

Joseph, M. B., M. W. Rossi, **N. P. Mietkiewicz**, A. L. Mahood, M. E. Cattau, L. A. St. Denis, R. C. Nagy, V. Iglesias, J. T. Abatzoglou, and J. K. Balch. 2018. Understanding and predicting extreme wildfires in the contiguous United States. bioRxiv; doi: https://doi.org/10.1101/384115

# Book Chapters

Rogan, J., and **N. Mietkiewicz**. 2015. *Land Cover Change Detection* in A. Aranganathan, editor. Land Resources Monitoring, Modeling, and Mapping with Remote Sensing.

# Current research appointment
**Postdoctoral Research Associate** \hfill 2016--present

*Earth Lab and the Cooperative Institute for Research in Environmental Sciences, University of Colorado at Boulder*

- -Deployed geospatial, reproducible workflows in a salable, cloud-compute environment via Amazon Web Services (AWS) leveraging Docker and GitHub to build stable, collaborative work environments across platforms.
- -Wrote clean, efficient, reproducible R code to analyze big geospatial data.
- -Built out and optimizing statistical models using a variety of techniques, with focus on machine learning algorithms.
- -Mentored/managed undergraduate and graduate level interns and research assistants.
- -Authored and co-authored 6 peer-review publications with 3 more in review and 10 in progress.
- -Authored and Co-authored over $15 million in research grant proposals.

**Research Assistant** \hfill 2013-2016

*Graduate School of Geography, Clark University, Worcester, MA*

- -Developed and led a successful field campaign located in the backcountry of the Colorado Rockies.
- -Managed a team of 8 undergraduate and graduate students in remote, mountainous areas for 18 weeks over the course of 2 summers.
- -Collected over 2,000 tree cores, 1,000 seedling/sampling samples, and data ranging over 3 projects, resulting in 4 peer-reviewed publications and my dissertation.
- -Synthesized field data that was fed into large wildfire behavior prediction models under current and 3 future climate scenarios across the Southern Rocky Mountains.
- -Managed the Forest Ecology Lab, where duties included maintaining, ordering, inventorying, and supporting both computer and field equipment for the research and classroom laboratories.

# Past research Appointments
\begin{tabular}{p{1cm}|p{15cm}}
2012                 & Research and Development, Clark Labs, Worcester, MA                                          \\
 &                                                                                              \\
2011                 & GIS Consultant, Department of Public Works, Ashland, MA                                      \\
                     & GIS Analyst, United States Department of Agriculture: National Resource Conservation Service \\
 &                                                                                              \\
2008                 & Field Researcher, Scott Glacier, Antarctica via University of Maine, Orono                   \\
 &                                                                                              \\
2007                 & Field Researcher, Marine Sediments Laboratory, University of Maine, Orono                    \\
 &                                                                                              \\
2006                 & Laboratory Technician, Climate Change Institute, University of Maine, Orono                  \\
 & Numerical Modeling Technician, Numerical Modeling Laboratory, University of Maine, Orono     \\
 &                                                                                              \\ 
\end{tabular}

# Teaching Appointments

\begin{tabular}{@{}llll@{}}
\multicolumn{4}{l}{\textbf{Faculty Positions}}                                             \\
 & \multicolumn{3}{l}{\textit{Clark University}}                                           \\
 &  & 2015 & Forest Ecology (GEOG 116); Overall Effectiveness = 4.6/5                      \\
 &  &      & \multicolumn{1}{c}{}                                                          \\
\multicolumn{4}{l}{\textbf{Teaching Assistant Positions}}                                  \\
 & \multicolumn{3}{l}{\textit{Clark University}}                                           \\
 &  & 2015 & Advanced Topics in GIS: Raster GIS (GEOG 397); Overall Effectiveness = 4.94/5 \\
 &  &      & \multicolumn{1}{c}{}                                                          \\
 &  & 2014 & Introduction to Remote Sensing (GEOG 383); Overall Effectiveness = 4.89/5     \\
 &  &      & Advanced Topics in GIS: Raster GIS (GEOG 397); Overall Effectiveness = 4.74/5 \\
 &  &      & \multicolumn{1}{c}{}                                                          \\
 &  & 2013 & Forest Ecology (GEOG 116); Overall Effectiveness = 4.62/5                     \\
 &  &      & Advanced Topics in GIS: Raster GIS (GEOG 397); Overall Effectiveness = 4.74/5 \\
 &  &      &                                                                               \\
 &  & 2012 & Earth System Science (GEOG 104); Overall Effectiveness = 4.97/5              
\end{tabular}

# Grants, Awards, and Fellowships

\begin{tabular}{p{1cm}|p{15cm}}
2019 & \$898,997 - NSF RIDIR Proposal: The next generation of historical settlement data products for the conterminous U.S. over 150 Years. Senior Personal. Pending.  \\ 
     &                                                                                                                              \\
2018 & \$1,287,690 - Macroscale Resilience: Assessing the recovery of western U.S. forests to compound disturbance and enabling continental-scale exploration of resilience through open NEON science. Senior Personal. Pending. \\
     & \$931,768 - CAREER: Fire impacts on forest carbon recovery in a warming world: training the next generation of Earth analysts by exploring a missing scale of observations. Postdoctoral Associate Support.  \\
     &                                                                                                                              \\
2017 & \$1200 - Fire Predicition Across Scales conference travel award - Columbia University                                        \\
     &                                                                                                                              \\
2015 & \$700 - Clark University’s Outstanding Teaching Assistant Award                                                              \\
     & \$300 - Marion I. Wright ’46 Travel Award, Fall 2015                                                                         \\
     & \$250 - Pruser Dissertation Enhancement Award                                                                                \\
     & \$300 - Graduate Student Council Travel Award, Spring 2016                                                                   \\
     &                                                                                                                              \\
2013 & \$600 - Marion I. Wright ’46 Travel Award, Spring/Fall 2013                                                                  \\
     & \$750 - Pruser Dissertation Enhancement Award                                                                                \\
     &                                                                                                                              \\
2012 & \$4,000 - Libbey Enhancement Award                                                                                           \\
     & \$55,000 - Full tuition remission and stipend (5 years, approx. per year)                                                    \\
     &                                                                                                                              \\
2010 & \begin{tabular}[c]{@{}l@{}}\$15,980 - Awarded scholarship towards Master’s degree (2 years, approx. per\\ year)\end{tabular} \\
     &                                                                                                                            
\end{tabular}

# Professional Presentations

2019 **Mietkiewicz, N.**. *Characterizing wildfire risk to the wildland-urban interface in the U.S.* IGNITE talk at the USDA Forest Service Stakeholder Workshop: Urban and Wildland-Urban Interface Forests Under Changing Conditions, Denver, CO, USA. Invitation.

2019 **Mietkiewicz, N. P.**, Balch, J. K., Schoennagel T., Leyk S., St. Denis L., Bradley B. A., *In the line of fire: Consequences of human-ignited wildfires to homes in the U.S. (1992-2015)*. Paper presentation at the International Association of Wildland Fire 6th Fire Behavior and Fuels Conference, Marseille, France. Invitation.

2019 **Mietkiewicz, N. P.**, Balch, J. K., Schoennagel T., Leyk S., St. Denis L., Bradley B. A. *In the line of fire: Consequences of human-ignited wildfires to homes in the U.S. (1992-2015)*. Poster presentation at the CIRES Rendezvous, Boulder, CO.

2019 **Mietkiewicz N.** *Modeling wildfire in the 21st century: big data and machine learning in the cloud*. Flashtalk at the North Central Climate Adaptation Science Center Open House, Boulder, CO. Invitation.

2019  **Mietkiewicz, N. P.**, Balch, J. K., Schoennagel T., Leyk S., St. Denis L., Bradley B. A. *In the line of fire: Consequences of human-ignited wildfires to homes in the U.S. (1992-2015)*. Poster presentation at the USGS North Central Climate Adaptation Science Center Open House, Boulder, CO. Invitation.

2017 **Mietkiewicz, N.**, Balch, J., St. Denis, L., Schoennagel, T. *Drivers of historic and future wildfire occurrence across the United States: the relative contribution of human ignitions vs climate to fire size and probability*.  Presentation at the Fire Prediction Across Scales Conference, Columbia University, New York City, NY, USA.

2017 **Mietkiewicz, N.**, Balch, J., St. Denis, L., *Human-ignited fires at the wildland-urban interface: consequences and costs*.  Presentation at the Ecological Society of America Portland, OR, USA.

2016 **Mietkiewicz, N.**, D. Kulakowski, and T.T. Veblen. *Spruce beetle legacies on fire behavior under a varying climate in CO, USA*. Paper presentation at the Association of American Geographers, San Francisco, CA.

2016 **Mietkiewicz, N.**, D. Kulakowski, and T.T. Veblen. *Spruce beetle legacies on fire behavior under a varying climate in CO, USA*. Poster presentation at the 5th International Fire Behavior and Fuels Conference, Portland, OR

2014 **Mietkiewicz, N.**, Kulakowski, D. *How do spruce beetle outbreaks affect fuel loads in the southern Rocky Mountains, CO*. Paper presented at the Association of American Geographers, Tampa, FL.

2013 **Mietkiewicz, N.**, Kulakowski, D., and Rogan, J. *Identifying sub-continental drivers of wildland fire under a varying climate*. Paper presented at New England-St. Lawrence Valley Geographical Society (NESTVAL), Worcester, MA.

2013 **Mietkiewicz, N.**, Kulakowski, D., and Rogan, J. *What are the landscape requirements preceding wildland fire occurrence?* Paper presented and Biogeography session chaired at the Annual Conference of the Association of American Geographers, Los Angeles, CA.

2012 **Mietkiewicz, N.**, Kulakowski, D., and Rogan, J. *A century of ecological change in a subalpine forest of the Swiss Alps*. Paper presented at the Annual Conference of the Association of American Geographers, New York, NY.

# Outreach, Synergistic Activities, and Professional Development

Peer-reviewed for the following journals: Ecology and Evolution, International Journal of Wildfire, Open Access Forests, Ecography.

2019 **Invited Participant** at the USDA Forest Service Stakeholder Workshop: Urban and Wildland-Urban Interface Forests Under Changing Conditions, Denver, CO.

2019 **Inviited Participant** at the USGS North Central Climate Adaptation Science Center Open House, Boulder, CO.

2019 **Invited Participant** at a Global WUI Working Group at the International Association of Wildland Fire 6th Fire Behavior and Fuels Conference, Marseille, France.

2018 **Invite Participant** in the Environmental Extremes CodeFest, Univeristy of Colorado, Boulder, CO.

2017 **Invited Speaker** in an undergraduate class, Introduction to Physical Geography, University of Colorado, Boulder, CO.

2017 **Participant** at the Rocky Mountain Advanced Computing Consortium 2017, University of Colorado, Boulder, CO.

2017 **Invited Speaker** at the Wildfire Information Development Workshop, Boulder, CO, USA. Entitled: Human-ignited fires at the wildland-urban interface: case study for using ICS-209s.  

2017 **Participant** at the NASA Wildland Fire Applications 2017 Team Meeting, University of Colorado, Boulder, CO.

2017 **Invited Speaker** at the Earth Science & Observation Center Colloquium, University of Colorado, Boulder, CO. Entitled: Earth Lab: Accelerating discovery with advanced earth analytics.

2014 **Participant** in a Seminar in College Teaching, Certificate in College Teaching. Colleges of Worcester Consortium, Inc.

2014 **Professional exhibitor** representing Clark Labs at the Annual Conference of the Association of American Geographers, Tampa, FL.

2014 **Professional exhibitor** representing Clark Labs at the American Society for Photogrammetry and Remote Sensing, Baltimore, MD.

2013 **Professional exhibitor** representing Clark Labs at the Annual Conference of the Association of American Geographers, Los Angeles, CA.

# Media Contributions

2019 J. Balch, M. Cattau, J. McGlinchy, **N. Mietkiewicz**, and V. Scholl worked with *PBS Nova* crew filming in Cold Springs wildfire field site for *Wildfires*.